### ISSUE TITLE
msg-handler-loop question

### ISSUE THREAD

**Issue by batwicket** [matthiasn/systems-toolbox#9]
Just curious why you aren't using an alts! to listen on messages in msg-handler-loop.

**Comment by matthiasn** [comment]
Sure. In my understanding, alts! would complete at most one of multiple channel operations that are ready, which here would be channels to take from. Since the two channels used here have such different characteristics, I also find it cleaner to completely separate the handlers for each type of channel.

**Comment by matthiasn** [comment]
I'll close this for now, but feel free to re-open anytime when you have more questions. I'm happy to discuss any aspect of the library. Cheers
